version: 1
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y/%m/%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: DEBUG
        stream: ext://sys.stdout
    file_loggerfilesformatter:
        class : logging.FileHandler
        formatter: simple
        level: DEBUG
        filename: '/home/marcus/data/ErkenLab-Data-Framework/loggerfilesformatter.log'
    file_ftpuploader:
        class : logging.FileHandler
        formatter: simple
        level: DEBUG
        filename: '/home/marcus/data/ErkenLab-Data-Framework/ftpuploader.log'
loggers:
    ftpuploader:
        level: DEBUG
        handlers: [console, file_ftpuploader]
    loggerfilesformatter:
        level: DEBUG
        handlers: [console, file_loggerfilesformatter]
root:
    handlers: [console]
    level: NOTSET